# Generated by Django 6.0.3 on 2026-05-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="案件名")),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=120, verbose_name="顧客名"),
                ),
                (
                    "drawing_pdf",
                    models.FileField(
                        blank=True, upload_to="drawings/", verbose_name="図面PDF"
                    ),
                ),
                (
                    "wallpaper_roll_width_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.92,
                        max_digits=5,
                        verbose_name="ロール幅(m)",
                    ),
                ),
                (
                    "wallpaper_roll_length_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="ロール長さ(m)",
                    ),
                ),
                (
                    "loss_rate_percent",
                    models.DecimalField(
                        decimal_places=1,
                        default=8,
                        max_digits=5,
                        verbose_name="ロス率(%)",
                    ),
                ),
                (
                    "unit_price_per_roll",
                    models.PositiveIntegerField(
                        default=11800, verbose_name="1ロール単価"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="部屋名")),
                (
                    "perimeter_m",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="周長(m)"
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.4,
                        max_digits=5,
                        verbose_name="天井高(m)",
                    ),
                ),
                (
                    "opening_area_m2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="開口部面積(m2)",
                    ),
                ),
                (
                    "ceiling_area_m2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="天井面積(m2)",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=160, verbose_name="備考"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="estimator.project",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
