# Generated by Django 6.0.3 on 2026-05-12 03:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="wallpaper_roll_width_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.92"),
                max_digits=5,
                verbose_name="ロール幅(m)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="height_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.4"),
                max_digits=5,
                verbose_name="天井高(m)",
            ),
        ),
    ]
