# Generated by Django 6.0.3 on 2026-05-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0004_rename_permission_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="page_1f_plan",
            field=models.CharField(
                default="5", max_length=8, verbose_name="1F平面図ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_2f_plan",
            field=models.CharField(
                default="6", max_length=8, verbose_name="2F平面図ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_3f_plan",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="3F平面図ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_east_elevation",
            field=models.CharField(
                default="7", max_length=8, verbose_name="東側立面図ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_north_elevation",
            field=models.CharField(
                default="7", max_length=8, verbose_name="北側立面図ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_section",
            field=models.CharField(
                default="8", max_length=8, verbose_name="断面図ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_south_elevation",
            field=models.CharField(
                default="7", max_length=8, verbose_name="南側立面図ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_west_elevation",
            field=models.CharField(
                default="7", max_length=8, verbose_name="西側立面図ページ"
            ),
        ),
    ]
