# Generated by Django 6.0.3 on 2026-05-14 03:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0005_project_page_1f_plan_project_page_2f_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstimateDefaultSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallpaper_roll_width_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.92"),
                        max_digits=5,
                        verbose_name="ロール幅(m)",
                    ),
                ),
                (
                    "wallpaper_roll_length_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=5,
                        verbose_name="ロール長さ(m)",
                    ),
                ),
                (
                    "loss_rate_percent",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("8"),
                        max_digits=5,
                        verbose_name="ロス率(%)",
                    ),
                ),
                (
                    "unit_price_per_roll",
                    models.PositiveIntegerField(
                        default=11800, verbose_name="1ロール単価"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "初期値設定",
                "verbose_name_plural": "初期値設定",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="page_1f_plan",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="1F平面図ページ"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="page_2f_plan",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="2F平面図ページ"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="page_east_elevation",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="東側立面図ページ"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="page_north_elevation",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="北側立面図ページ"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="page_section",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="断面図ページ"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="page_south_elevation",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="南側立面図ページ"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="page_west_elevation",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="西側立面図ページ"
            ),
        ),
    ]
