# Generated by Django 6.0.3 on 2026-05-25 06:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_wallpapers_and_snapshots(apps, schema_editor):
    Wallpaper = apps.get_model("estimator", "Wallpaper")
    EstimateDefaultSettings = apps.get_model("estimator", "EstimateDefaultSettings")
    Project = apps.get_model("estimator", "Project")
    Room = apps.get_model("estimator", "Room")

    none_wallpaper, _created = Wallpaper.objects.get_or_create(
        number="000",
        defaults={
            "display_order": "000",
            "name": "壁紙無し",
            "roll_width_m": Decimal("0"),
            "roll_length_m": Decimal("0"),
            "loss_rate_percent": Decimal("0"),
            "unit_price_per_roll": 0,
            "is_active": True,
        },
    )
    standard_wallpaper, _created = Wallpaper.objects.get_or_create(
        number="001",
        defaults={
            "display_order": "001",
            "name": "標準壁紙",
            "roll_width_m": Decimal("0.92"),
            "roll_length_m": Decimal("50"),
            "loss_rate_percent": Decimal("8"),
            "unit_price_per_roll": 11800,
            "is_active": True,
        },
    )

    for defaults in EstimateDefaultSettings.objects.all():
        if defaults.default_wallpaper_id is None:
            defaults.default_wallpaper_id = standard_wallpaper.pk
            defaults.save(update_fields=["default_wallpaper"])

    surfaces = ("east", "west", "south", "north", "ceiling")
    for project in Project.objects.all():
        use_none = (
            project.wallpaper_roll_width_m <= 0
            or project.wallpaper_roll_length_m <= 0
            or project.unit_price_per_roll <= 0
        )
        for room in Room.objects.filter(project=project):
            if use_none:
                values = {
                    "wallpaper_no": none_wallpaper.number,
                    "wallpaper_name": none_wallpaper.name,
                    "roll_width_m": none_wallpaper.roll_width_m,
                    "roll_length_m": none_wallpaper.roll_length_m,
                    "loss_rate_percent": none_wallpaper.loss_rate_percent,
                    "unit_price_per_roll": none_wallpaper.unit_price_per_roll,
                }
            else:
                values = {
                    "wallpaper_no": "001",
                    "wallpaper_name": standard_wallpaper.name,
                    "roll_width_m": project.wallpaper_roll_width_m,
                    "roll_length_m": project.wallpaper_roll_length_m,
                    "loss_rate_percent": project.loss_rate_percent,
                    "unit_price_per_roll": project.unit_price_per_roll,
                }
            for surface in surfaces:
                setattr(room, f"{surface}_wallpaper_no", values["wallpaper_no"])
                setattr(room, f"{surface}_wallpaper_name", values["wallpaper_name"])
                setattr(room, f"{surface}_roll_width_m", values["roll_width_m"])
                setattr(room, f"{surface}_roll_length_m", values["roll_length_m"])
                setattr(room, f"{surface}_loss_rate_percent", values["loss_rate_percent"])
                setattr(room, f"{surface}_unit_price_per_roll", values["unit_price_per_roll"])
            room.save()


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0007_create_default_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallpaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.CharField(
                        default="999", max_length=3, verbose_name="表示順"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=3, unique=True, verbose_name="壁紙No."),
                ),
                ("name", models.CharField(max_length=80, verbose_name="壁紙名称")),
                (
                    "roll_width_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.92"),
                        max_digits=5,
                        verbose_name="ロール幅(m)",
                    ),
                ),
                (
                    "roll_length_m",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=5,
                        verbose_name="ロール長さ(m)",
                    ),
                ),
                (
                    "loss_rate_percent",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("8"),
                        max_digits=5,
                        verbose_name="ロス率(%)",
                    ),
                ),
                (
                    "unit_price_per_roll",
                    models.PositiveIntegerField(
                        default=11800, verbose_name="1ロール単価"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "壁紙マスタ",
                "verbose_name_plural": "壁紙マスタ",
                "ordering": ["display_order", "number"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="adopted_estimate_method",
            field=models.CharField(
                choices=[
                    ("wallpaper_total", "壁紙別合算方式"),
                    ("room_total", "部屋別積上方式"),
                ],
                default="wallpaper_total",
                max_length=24,
                verbose_name="採用見積方式",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ceiling_loss_rate_percent",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("8"),
                max_digits=5,
                verbose_name="天井 ロス率(%)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ceiling_roll_length_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50"),
                max_digits=5,
                verbose_name="天井 ロール長さ(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ceiling_roll_width_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.92"),
                max_digits=5,
                verbose_name="天井 ロール幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ceiling_unit_price_per_roll",
            field=models.PositiveIntegerField(
                default=11800, verbose_name="天井 1ロール単価"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ceiling_wallpaper_name",
            field=models.CharField(
                default="標準壁紙", max_length=80, verbose_name="天井 壁紙名称"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ceiling_wallpaper_no",
            field=models.CharField(
                default="001", max_length=3, verbose_name="天井 壁紙No."
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_loss_rate_percent",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("8"),
                max_digits=5,
                verbose_name="東壁面 ロス率(%)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_roll_length_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50"),
                max_digits=5,
                verbose_name="東壁面 ロール長さ(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_roll_width_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.92"),
                max_digits=5,
                verbose_name="東壁面 ロール幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_unit_price_per_roll",
            field=models.PositiveIntegerField(
                default=11800, verbose_name="東壁面 1ロール単価"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_wallpaper_name",
            field=models.CharField(
                default="標準壁紙", max_length=80, verbose_name="東壁面 壁紙名称"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_wallpaper_no",
            field=models.CharField(
                default="001", max_length=3, verbose_name="東壁面 壁紙No."
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_loss_rate_percent",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("8"),
                max_digits=5,
                verbose_name="北壁面 ロス率(%)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_roll_length_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50"),
                max_digits=5,
                verbose_name="北壁面 ロール長さ(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_roll_width_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.92"),
                max_digits=5,
                verbose_name="北壁面 ロール幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_unit_price_per_roll",
            field=models.PositiveIntegerField(
                default=11800, verbose_name="北壁面 1ロール単価"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_wallpaper_name",
            field=models.CharField(
                default="標準壁紙", max_length=80, verbose_name="北壁面 壁紙名称"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_wallpaper_no",
            field=models.CharField(
                default="001", max_length=3, verbose_name="北壁面 壁紙No."
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_loss_rate_percent",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("8"),
                max_digits=5,
                verbose_name="南壁面 ロス率(%)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_roll_length_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50"),
                max_digits=5,
                verbose_name="南壁面 ロール長さ(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_roll_width_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.92"),
                max_digits=5,
                verbose_name="南壁面 ロール幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_unit_price_per_roll",
            field=models.PositiveIntegerField(
                default=11800, verbose_name="南壁面 1ロール単価"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_wallpaper_name",
            field=models.CharField(
                default="標準壁紙", max_length=80, verbose_name="南壁面 壁紙名称"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_wallpaper_no",
            field=models.CharField(
                default="001", max_length=3, verbose_name="南壁面 壁紙No."
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_loss_rate_percent",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("8"),
                max_digits=5,
                verbose_name="西壁面 ロス率(%)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_roll_length_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50"),
                max_digits=5,
                verbose_name="西壁面 ロール長さ(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_roll_width_m",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.92"),
                max_digits=5,
                verbose_name="西壁面 ロール幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_unit_price_per_roll",
            field=models.PositiveIntegerField(
                default=11800, verbose_name="西壁面 1ロール単価"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_wallpaper_name",
            field=models.CharField(
                default="標準壁紙", max_length=80, verbose_name="西壁面 壁紙名称"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_wallpaper_no",
            field=models.CharField(
                default="001", max_length=3, verbose_name="西壁面 壁紙No."
            ),
        ),
        migrations.AddField(
            model_name="estimatedefaultsettings",
            name="default_wallpaper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="estimator.wallpaper",
                verbose_name="デフォルト壁紙",
            ),
        ),
        migrations.RunPython(seed_wallpapers_and_snapshots, migrations.RunPython.noop),
    ]
