# Generated by Django 6.0.3 on 2026-05-26 01:37

from decimal import Decimal
from django.db import migrations, models


def seed_surface_measurements(apps, schema_editor):
    Room = apps.get_model("estimator", "Room")
    for room in Room.objects.all():
        wall_surface_area = (room.perimeter_m * room.height_m) / Decimal("4")
        wall_opening_area = room.opening_area_m2 / Decimal("4")
        room.east_surface_area_m2 = wall_surface_area
        room.west_surface_area_m2 = wall_surface_area
        room.south_surface_area_m2 = wall_surface_area
        room.north_surface_area_m2 = wall_surface_area
        room.ceiling_surface_area_m2 = room.ceiling_area_m2
        room.east_opening_area_m2 = wall_opening_area
        room.west_opening_area_m2 = wall_opening_area
        room.south_opening_area_m2 = wall_opening_area
        room.north_opening_area_m2 = wall_opening_area
        room.save()


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0008_wallpaper_project_adopted_estimate_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="ceiling_surface_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="天井 面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_opening_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="東壁面 開口部面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_surface_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="東壁面 面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_opening_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="北壁面 開口部面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_surface_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="北壁面 面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_opening_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="南壁面 開口部面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_surface_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="南壁面 面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_opening_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="西壁面 開口部面積(m2)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_surface_area_m2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=7,
                verbose_name="西壁面 面積(m2)",
            ),
        ),
        migrations.RunPython(seed_surface_measurements, migrations.RunPython.noop),
    ]
