# Generated by Django 6.0.3 on 2026-05-29 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0009_room_ceiling_surface_area_m2_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="drawing_pdf_content_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="図面PDF MIMEタイプ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drawing_pdf_original_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="図面PDF 元ファイル名"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drawing_pdf_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="図面PDF サイズ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="drawing_pdf_storage_path",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="図面PDF Storageパス"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="アップロードユーザー",
            ),
        ),
    ]
