# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0010_project_drawing_pdf_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="page_east_elevation",
        ),
        migrations.RemoveField(
            model_name="project",
            name="page_north_elevation",
        ),
        migrations.RemoveField(
            model_name="project",
            name="page_section",
        ),
        migrations.RemoveField(
            model_name="project",
            name="page_south_elevation",
        ),
        migrations.RemoveField(
            model_name="project",
            name="page_west_elevation",
        ),
        migrations.AddField(
            model_name="project",
            name="page_1f_ceiling_plan",
            field=models.CharField(default="ー", max_length=8, verbose_name="1F天井伏図ページ"),
        ),
        migrations.AddField(
            model_name="project",
            name="page_1f_development",
            field=models.CharField(default="ー", max_length=8, verbose_name="1F展開図ページ"),
        ),
        migrations.AddField(
            model_name="project",
            name="page_2f_ceiling_plan",
            field=models.CharField(default="ー", max_length=8, verbose_name="2F天井伏図ページ"),
        ),
        migrations.AddField(
            model_name="project",
            name="page_2f_development",
            field=models.CharField(default="ー", max_length=8, verbose_name="2F展開図ページ"),
        ),
        migrations.AddField(
            model_name="project",
            name="page_3f_ceiling_plan",
            field=models.CharField(default="ー", max_length=8, verbose_name="3F天井伏図ページ"),
        ),
        migrations.AddField(
            model_name="project",
            name="page_3f_development",
            field=models.CharField(default="ー", max_length=8, verbose_name="3F展開図ページ"),
        ),
    ]
