# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0011_update_project_drawing_page_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="page_1f_development",
            new_name="page_development_start",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="page_2f_development",
            new_name="page_development_end",
        ),
        migrations.AlterField(
            model_name="project",
            name="page_development_start",
            field=models.CharField(default="ー", max_length=8, verbose_name="展開図開始ページ"),
        ),
        migrations.AlterField(
            model_name="project",
            name="page_development_end",
            field=models.CharField(default="ー", max_length=8, verbose_name="展開図終了ページ"),
        ),
        migrations.RemoveField(
            model_name="project",
            name="page_3f_development",
        ),
    ]
