# Generated by Django 6.0.3 on 2026-06-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0013_room_source_and_summary_exclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_calculation_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="直近計算時間(秒)"
            ),
        ),
    ]
