# Generated by Django 6.0.3 on 2026-06-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0014_project_last_calculation_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="analysis_error_message",
            field=models.TextField(blank=True, verbose_name="解析エラーメッセージ"),
        ),
        migrations.AddField(
            model_name="project",
            name="analysis_finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="解析終了日時"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="analysis_model",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="解析モデル"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="analysis_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="解析開始日時"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未実行"),
                    ("pending", "待機中"),
                    ("running", "解析中"),
                    ("succeeded", "解析完了"),
                    ("failed", "解析失敗"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="解析ステータス",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_finish_table",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="室内仕上表ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_fixture_table_end",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="建具表終了ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_fixture_table_start",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="建具表開始ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_floor_area_table",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="床面積表ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_internal_finish_table",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="内部仕上表ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_living_area_table",
            field=models.CharField(
                default="ー", max_length=8, verbose_name="居室区画面積表ページ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_other_tables",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="その他表ページ"
            ),
        ),
    ]
