# Generated by Django 6.0.3 on 2026-06-26 06:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0015_project_analysis_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="ceiling_surface_height_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="天井 高(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="ceiling_surface_width_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="天井 幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_surface_height_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="東壁面 高(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="east_surface_width_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="東壁面 幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_surface_height_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="北壁面 高(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="north_surface_width_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="北壁面 幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_surface_height_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="南壁面 高(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="south_surface_width_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="南壁面 幅(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_surface_height_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="西壁面 高(m)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="west_surface_width_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="西壁面 幅(m)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="ceiling_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="天井面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="ceiling_surface_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="天井 面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="east_opening_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="東壁面 開口部面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="east_surface_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="東壁面 面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="height_m",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("2.4"),
                max_digits=6,
                verbose_name="天井高(m)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="north_opening_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="北壁面 開口部面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="north_surface_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="北壁面 面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="opening_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="開口部面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="perimeter_m",
            field=models.DecimalField(
                decimal_places=3, max_digits=8, verbose_name="周長(m)"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="south_opening_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="南壁面 開口部面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="south_surface_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="南壁面 面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="west_opening_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="西壁面 開口部面積(m2)",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="west_surface_area_m2",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="西壁面 面積(m2)",
            ),
        ),
        migrations.CreateModel(
            name="RoomSurfaceOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.CharField(max_length=12, verbose_name="面")),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(verbose_name="開口部番号"),
                ),
                (
                    "width_m",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="幅(m)",
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="高(m)",
                    ),
                ),
                (
                    "area_m2",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="面積(m2)",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openings",
                        to="estimator.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "開口部",
                "verbose_name_plural": "開口部",
                "ordering": ["room_id", "surface", "sequence"],
                "unique_together": {("room", "surface", "sequence")},
            },
        ),
    ]
