# Generated by Django 6.0.3 on 2026-06-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimator", "0016_room_ceiling_surface_height_m_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="note",
            field=models.TextField(blank=True, verbose_name="備考"),
        ),
    ]
